version: '3.7'

services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    restart: always
    expose:
      - 3306
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD="PASSWORD" #CHANGE ME
      - MYSQL_PASSWORD="PASSWORD" #CHANGE ME
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: always
    ports:
      - 8080:80
    links:
      - mariadb
      - redis
#      - collabora
#      - imaginary
    depends_on:
      - mariadb
      - redis
#      - collabora
    volumes:
      - ./nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD="PASSWORD" #CHANGE ME
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=mariadb
      - REDIS_HOST=redis
      - REDIS_PORT=6379
#      - SMTP_HOST=192.168.4.201
#      - SMTP_PORT=25
#      - SMTP_AUTHTYPE=LOGIN
#      - SMTP_NAME=EMAIL_HERE
#      - SMTP_PASSWORD=PASSWORD
#      - MAIL_FROM_ADDRESS=FROM_ADDRESS
#      - MAIL_DOMAIN=DOMAIN
      - PHP_MEMORY_LIMIT=512M
      - PHP_UPLOAD_LIMIT-100M
      - TRUSTED_PROXIES=192.168.4.204 #CHANGE ME
#      - NVIDIA_VISIBLE_DEVICES=all
#      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: "nvidia"
#              count: 1
#              capabilities: [gpu]

  redis:
    container_name: redis
    image: redis:latest
    expose:
      - 6379
    command: redis-server --save 60 1 --loglevel warning
    restart: always

#  collabora:
#    container_name: collabora
#    hostname: collabora
#    privileged: true
#    tty: true
#    ports:
#      - 9980:9980
#    cap_add:
#      - MKNOD
#    image: collabora/code:latest
#    volumes:
#      - ./collabora/config/coolwsd.xml:/etc/coolwsd/coolwsd.xml
#      - /etc/letsencrypt/live/<domain>.com/cert.pem:/etc/coolwsd/cert.pem:ro
#      - /etc/letsencrypt/live/<domain>.com/privkey.pem:/etc/coolwsd/key.pem:ro
#      - /etc/letsencrypt/live/<domain>.com/fullchain.pem:/etc/coolwsd/ca-chain.cert.pem:ro
#    environment:
#      - username=admin
#      - password=PASSWORD
#      - domain=cloud\\.<domain>\\.com
#    restart: always

#  nats:
#    image: nats:2.2.1
#    container_name: nats
#  #  volumes:
#  #    - ./nats/config:/config/
#  #  command: ["-c", "/config/gnatsd.conf"]
#    ports:
#      - 4222:4222
#    restart: unless-stopped

 # janus:
 #   build: janus
 #   container_name: janus
 #   command: ["janus", "--full-trickle"]
 #   network_mode: host
 #   restart: unless-stopped

#  imaginary:
#    image: nextcloud/aio-imaginary:latest
#    container_name: imaginary
#    restart: always
#    environment:
#      - PORT=9000
#    ports:
#      - 9000:9000
#    command: -concurrency 50 -enable-url-source -log-level debug
